# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Art Of The Less
email: artoftheless@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A conscious effort to improve myself every single day of my life, so that 
  I can be of service to myself and to my community.
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://wildflame.me" # the base hostname & protocol for your site
#twitter_username: Taffyer 
#github_username:  wild-flame 

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
# google_analytics: 
disqus_shortname: artoftheless

# used this for post_excerpt at index_page
excerpt_separator: <!--readmore-->
